spring.application.name=testcontainers-implementation

#Define local instance db connectivity
spring.datasource.url=jdbc:h2:mem:${H2_DB_DATABASE_NAME}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${H2_DB_USERNAME}
spring.datasource.password=


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2